@startuml
title Контекст Системы отопления

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы")

Container_Boundary(clientApp, "Клиентское приложение Умного дома") {
  Component(webComponent, "Wep APP Component", $techn="COMPONENT TYPE", $tags="v1", $descr="Component and boundary use different tag name spaces that both v1 tags can use different styles")
  Component(mobileComponent, "Mobile Component", $techn="COMPONENT TYPE", $tags="v1", $descr="Component and boundary use different tag name spaces that both v1 tags can use different styles")
}

Container_Boundary(brokerMassage, "Брокер сообщений") {
  Component(kafkaComponent, "Kafka", $descr="Шина для интеграции микросервисов")
}

Container_Boundary(deviceGatewayThing, "Шлюз Устройств") {
  Component(deviceGatewayThingComponent, "API Gateway Thing", $descr="Реализует взаимодействие с устройстами")
}

Container_Boundary(APIGateway, "API Gateway") {
  Component(gatewayAPIComponent, "Kong", $descr="Предоставляет API")
}
System_Boundary(ThingSystem, "Система Устроств") {
  Container(Light, "Устройство освещения", "Предоставляет API устройста освещения")
  Container(Heating, "Устройство обогрева", "Предоставляет API устройста обогрева")
  Container(Viewing, "Устройство наблюдения", "Предоставляет API устройста наблюдения")
}



Rel(deviceGatewayThingComponent, Light, "Запрос данных и вызов API")
Rel(deviceGatewayThingComponent, Heating, "Запрос данных и вызов API")
Rel(deviceGatewayThingComponent, Viewing, "Запрос данных и вызов API")
Rel(deviceGatewayThingComponent, kafkaComponent, "Публикует данные")
Rel(kafkaComponent, deviceGatewayThingComponent, "Отправляет сообщшения устройствам")
Rel(user, webComponent, "Использует функционал умного дома")
Rel(user, mobileComponent, "Использует функционал умного дома")
Rel(clientApp, APIGateway, "Обращается к API")
@enduml


